import "./globals.css";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "portfolio",
  description: "Generated by Next.js",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // sesuaikan kebutuhan
  variable: "--font-poppins",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="bg-slate-900">{children}</body>
    </html>
  );
}
